carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('vaciar', views.clear, name='clear')
]

jaguarete_store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('acerca/', views.about, name='about'),
    path('', ProductListView.as_view(), name='index'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('nuevo/', views.new, name='new'),
    path('<slug:slug>/editar', views.edit, name='edit'),
    path('<slug:slug>/borrar', views.delete, name='delete'),
]

products/models.py
from django.db import models
from django.utils.text  import slugify
from django.db.models.signals import pre_save
import uuid

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=16, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

def set_slug(sender, instance , *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8])
            )
        instance.slug = slug

pre_save.connect(set_slug, sender=Product)

products/forms.py
from products.models import Product
from django import forms
from categories.models import Category

class NewProductForm(forms.Form):
    title = forms.CharField(label='Titulo del Producto', required=True, min_length=4, max_length=50, widget=forms.TextInput(attrs={
        'class':'form-control', 'id':'title'
    }))
    description = forms.CharField(label='Descripción',required=True, widget=forms.Textarea(attrs={
        'class':'form-control', 'id':'description'
    }))
    category = forms.ModelChoiceField(label='Categoría', queryset=Category.objects.all(), required=False, widget=forms.Select(attrs={
        'class':'form-control', 'id':'category'
    }))
    price = forms.DecimalField(label='Precio',max_digits=16, decimal_places=2, widget=forms.NumberInput(attrs={
        'class':'form-control', 'id':'price'
    }))
    image = forms.ImageField(label='Imagen del Producto', required=True, widget=forms.FileInput(attrs={
        'class':'form-control', 'id':'image', 'name':'image'
    }))

products/views.py
from django.db.models.query_utils import Q
from products.models import Product
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Product
from django.contrib.auth.decorators import user_passes_test
from .forms import NewProductForm
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from categories.models import Category

# Create your views here.

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')
    
    # Esto es una negrada pero funciona
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Productos'
        context['cards'] = self.queryset[:3]         
        context['list'] = self.queryset[3:]
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context  

class ProductSearchListView(ListView):
    template_name = 'products/search.html' 
    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)
    def query(self):
        return self.request.GET.get('q')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query 
        context['count'] = context['product_list'].count()
        return context

@user_passes_test(lambda user: user.is_superuser)
def new(request):
    form = NewProductForm(request.POST, request.FILES)
    if request.method == 'POST' and form.is_valid():
        title = form.data.get('title')
        description = form.data.get('description')
        price = form.data.get('price')
        cat_id = form.data.get('category')
        product = Product(title=title, image=request.FILES['image'], description=description, price=price)
        product.save()
        if cat_id:
            category = get_object_or_404(Category, id=cat_id)
            category.save()
            category.products.add(product)
        if product:
            messages.success(request, 'Producto agregado exitosamente')
            return redirect('index')
    return render(request, 'products/new.html',{
        'form':form ,
        'title': 'Nuevo Producto'
    })

@user_passes_test(lambda user: user.is_superuser)
def edit(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form = NewProductForm(request.POST, request.FILES)
    if request.method == 'POST' and form.is_valid():
        product.title = form.data.get('title')
        product.description = form.data.get('description')
        product.price = form.data.get('price')
        cat_id = form.data.get('category')
        product.image = request.FILES['image']
        product.save()
        if cat_id:
            category = get_object_or_404(Category, id=cat_id)
            category.save()
            category.products.add(product)
        if product:
            messages.success(request, 'Producto editado exitosamente')
            return redirect('index')
    return render(request, 'products/new.html',{
    'form':form ,
    'title': 'Actualizar Producto'
    })   

@user_passes_test(lambda user: user.is_superuser)
def delete(request, slug):
    product = get_object_or_404(Product, slug=slug)
    product.delete()
    return redirect('index')

products/templates/products/snippets/cards.html
<div class="row row-cols-1 row-cols-md-3 g-2">
    {% for product in cards %}
        <div class="col">
            {% include 'products/snippets/product.html' %}
        </div>
    {% endfor %}
</div> 

products/templates/products/snippets/list.html
        <h3 class="mt-2">Mas productos</h3>
        <div class="card">
            <ul class="list-group">
                    {% for product in list %}
                        <a class="list-group-item list-group-item-action" href="{% url 'products:product' product.slug %}">
                            <span class="fw-bolder">{{ product.title }}</span>
                            <span class="fw-light">{{ product.description }}</span>
                        </a> 
                    {% endfor %}
            </ul>
        </div>

products/templates/products/snippets/product.html
<div class="card" style="width: 18rem; border-radius: 30px; width:234px;" >
    <div class="card-body border border-2" style="border-radius: 30px; width:234px;">
        <h5 class="card-title">{{ product.title }}</h5>
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="Imagen del Producto" class="card-img-top" height="300" style="border-radius: 10px;">
        {% endif %}
        <p class="card-text">{{ product.description }}</p>
        <a href="{% url 'products:product' product.slug %}" class="btn btn-primary">Ver</a>
        {% if user.is_superuser %}
        <a href="{% url 'products:edit' product.slug %}" class="btn btn-secondary">Editar</a>
        <a href="{% url 'products:delete' product.slug %}" class="btn btn-danger">Eliminar</a>
        {% endif %}                    
    </div>
</div>

products/templates/products/snippets/search.html
<div class="card mt-3">
    <ul class="list-group">
            {% for product in object_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'products:product' product.slug %}">
                    <span class="fw-bolder">{{ product.title }}</span>
                    <span class="fw-light">{{ product.description }}</span>
                </a> 
            {% endfor %}
    </ul>
</div>