carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('vaciar', views.clear, name='clear')
]

jaguarete_store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('acerca/', views.about, name='about'),
    path('', ProductListView.as_view(), name='index'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('nuevo/', views.new, name='new'),
    path('<slug:slug>/editar', views.edit, name='edit'),
    path('<slug:slug>/borrar', views.delete, name='delete'),
]

templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{title}}</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent bibendum metus pellentesque dolor sollicitudin lobortis. 
        Duis vel ex scelerisque, porttitor nisl a, euismod arcu.
        Nam sagittis lobortis lacinia. Donec faucibus nulla nec justo sodales, eu aliquet quam laoreet. Aenean blandit lectus eget felis luctus, in aliquam nulla rhoncus. Maecenas justo turpis, accumsan convallis erat non, elementum varius tellus. 
        Quisque vel elementum mi. Suspendisse vitae imperdiet leo, vel molestie ex. Vestibulum ac mattis massa. Nunc rhoncus in nunc non aliquet. Aenean fringilla enim viverra quam ullamcorper lobortis. Donec euismod placerat diam, eget dignissim tortor tempor vel.

        Aliquam pulvinar tellus quis est egestas, id pretium ipsum efficitur. 
        Praesent sagittis turpis auctor, mattis sapien et, rutrum purus. Proin eget elit lobortis, accumsan velit eu, viverra magna. Pellentesque a nunc blandit risus dapibus feugiat vitae vitae augue. Aenean luctus congue ligula in maximus. Sed ante nisl, viverra id vulputate vitae, scelerisque vel nulla. Nulla facilisi. Pellentesque ullamcorper ullamcorper semper. Aliquam aliquam ligula velit, vitae pellentesque nisl rutrum ac. Phasellus porta lacus vel odio mollis imperdiet. Donec accumsan elit nec consequat lacinia. Nam ac sem sollicitudin sem porta consectetur.


    </p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jaguarete KAA Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column h-100" style="background-color: #cccccc;">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    <main class="flex-shrink-0">
        <div class="container">
            <div class="row mt-5 mb-5">
                {% include 'messages.html' %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    {% include 'footer.html' %}    
</body>
<script src="https://kit.fontawesome.com/f8d866bab6.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/footer.html
<footer class="bg-dark text-center text-white mt-auto p-3">

  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="https://www.facebook.com/"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="https://twitter.com/"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="https://www.instagram.com/"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>
      <!-- Reddit -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #ca7200;"
          href="https://www.reddit.com/"
          role="button"
          ><i class="fab fa-reddit"></i
        ></a>
      <!-- Youtube -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #ca0000;"
          href="https://www.youtube.com/"
          role="button"
          ><i class="fab fa-youtube"></i
        ></a>
      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="https://www.linkedin.com/"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="https://github.com/"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>

  <div class="container">
    Jaguarete KAA S.A © 2021 Copyright:
    <a class="text-white" href="https://github.com/Alexander0z">Alexander</a>
  </div>
</footer>

templates/header.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
    <h1 style="color: rgb(211, 211, 211);">Jaguarete KAA</h1>
    <img src= "{% static 'images/jaguarete.jpg' %}" alt="Acá va el logo" width="100px" style="border-radius: 50px;">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-2">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link">
          <span class="fas fa-user"></span>
          {{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == logout %}active{% endif %}" href="{{ logout }}">
          <span class="fas fa-sign-in-alt"></span>
          Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == login %}active{% endif %}" href="{{ login }}">
          <span class="fas fa-user"></span>
          Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == register %}active{% endif %}" href="{{ register }}">
          <span class="fas fa-user-plus"></span>
          Registro</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == cart %}active{% endif %}" href="{{ cart }}">
          <span class="fas fa-shopping-cart"></span>
          Carrito</a>
        </li>                      
      </ul>
    </div>
  </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="col">
    <h1>{{ title }}</h1>
    <div class="d-flex justify-content-center">
    {% include 'products/snippets/cards.html' %}
    </div>
    {% include 'products/snippets/list.html' %}
</div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
        <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
        {{ message }}
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'index' as index %}
{% url 'about' as about %}
{% url 'products:new' as new %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categorías
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Figuras">Figuras</a></li>
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Juegos">Juegos</a></li>
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Consolas">Consolas</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == about %}active{% endif %}" href="{{ about }}">Acerca de...</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:jaguaretekaa@correo.com">Contacto</a>
        </li> 
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == new %}active{% endif %}" href="{{ new }}">Nuevo Producto</a>
        </li>
        {% endif %}                        
      </ul>
      <form class="d-flex" action="{% url 'products:search' %}">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" name="q" value="{{ query }}">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>